### ISSUE TITLE
How to input sequence length filter information using filter protein by regular expression option?

### ISSUE THREAD

**Issue by BenSamy2020** [compomics/dbtoolkit#6]
Greetings,

I would like to thank you for providing an  open source database processing tool.

I am currently trying to place a protein length filter, to filter out sequences lesser than or equal to 6 amino acid from my fasta peptide database. I am unsure what to key-in the options provided. Please do advise me on how I can proceed?

Regards,
Ben

![Image_1](https://user-images.githubusercontent.com/69944967/93330555-4d903000-f862-11ea-9aab-4189354fec00.JPG)

**Comment by lnnrt** [comment]
Hi Ben,

Actually, if all you want is to filter by sequence, you're better off going via the 'File' --> 'Process' menu after you've loaded your database into DBToolkit (admittedly, it's a bit counterintuitive). The attached screenshot shows the menu on the left with a blue arrow.

In the processing dialog that pops up, choose 'Filter only' at the bottom of the first (large) panel (see selection in screenshot on right (blue arrow halfway down)). Of course, at the top, you should select the appropriate filter, which in your case is the FASTA SequenceLength filter (blue arrow at top), and then specify which length cutoff you'd like. Note that if you specify '<6' (as in the example, second blue arrow on top), only sequences less than or equal to 6 will be present in the output database. Conversely, if you would specify '>6', then only sequences larger or equal to 6 will be present in the output database.

Based on your question, I think what you want to filter by, is '>7', which will output a database containing all sequences of length 7 or more.

If you're happy with DBToolkit, please do not forget to cite it (http://www.ncbi.nlm.nih.gov/pubmed/16030071).

Cheers,

lnnrt.

![dbtoolkit](https://user-images.githubusercontent.com/6803230/93434804-e6f22d00-f8c8-11ea-9a9b-d0c2b1620a94.png)

**Comment by BenSamy2020** [comment]
Greetings lnnrt,

Thank you for your prompt reply. 

By any chance do you have an updated help file for dbtoolkit where I can find the different commands that I can utilise to manipulate my database of interest (e.g. protein length range 7AA - 50AA).

Lastly, I am not just happy with your open-source tool mate, I love it!. Will definitely site it in my upcoming publication!

Regards,
Ben

**Comment by lnnrt** [comment]
Hi,

Actually, I never implemented a boolean combination of length filters (while I could have), as I thought it was almost just as easy to concatenate the steps. So you first filter your source database using the abovementioned steps and with ">7", and you then load the resulting database in, and process again, but now with "<50" as the length filter parameter.

It's actually very quick and easy to do this.

PS: if you process lots of databases, or want to create series of databases, you can access all functionality on the command line, and script all of these things.

**Comment by BenSamy2020** [comment]
Hi Innrt,

Thanks mate! I am processing only a couple of cell line specific protein databases. I will do as what you said above.

Thanks.
